apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-oidc-replicaset
  labels:
    app: sample-oidc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-oidc
  template:
    metadata:
      labels:
        app: sample-oidc
    spec:
      containers:
      - name: sample-container
        image: jotron.com/sample-oidc:202505131342
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: minikube-cert
          mountPath: /usr/local/share/ca-certificates/minikube.local.crt
          subPath: tls.crt
        - name: root-cert
          mountPath: /usr/local/share/ca-certificates/root.crt
          subPath: tls.crt
        env:
        - name: KC_ADDR
          value: "https://minikube.local"
        - name: KC_REALM
          value: "master"
        - name: CLIENT_ID
          value: "trondoc"
        - name: CLIENT_SECRET
          value: "VLlVMrZY2pSddCtC6tVG64tTIJLD2zVt"
        - name: HOSTIP
          value: "127.0.0.1"
        - name: CLIENT_APP_NAME
          value: "myapp"
        command:
        - /bin/sh
        - -c
        - |
          update-ca-certificates && exec apache2-foreground
      volumes:
      - name: minikube-cert
        secret:
          secretName: minikube-tls
      - name: root-cert
        secret:
          secretName: root-crt
---
apiVersion: v1
kind: Service
metadata:
  name: sample-oidc
spec:
  selector:
    app: sample-oidc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 'sample-oidc-ingress'
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/forwarded-for-header: "X-Forwarded-For"
spec:
  ingressClassName: nginx
  rules:
    - host: 'minikube.local'
      http:
        paths:
          - path: /sample-oidc(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: 'sample-oidc'
                port:
                  number: 80
  tls:
    - hosts:
      - minikube.local
      secretName: 'minikube-tls'
